# Generated by Django 5.2 on 2025-04-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault_app', '0002_vaultentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaultEntry',
        ),
    ]
