# Generated by Django 5.2 on 2025-04-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault_app', '0003_delete_vaultentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='title',
        ),
    ]
