# Generated by Django 5.2 on 2025-04-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_app', '0006_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
