# Generated by Django 5.2 on 2025-04-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_app', '0009_passwordentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
