# Generated by Django 5.2 on 2025-04-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_app', '0010_monthlytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mood', models.CharField(blank=True, max_length=100, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyTask',
        ),
    ]
