# Generated by Django 5.2 on 2025-04-19 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_app', '0011_diaryentry_delete_monthlytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
