# Generated by Django 5.2 on 2025-04-20 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_app', '0012_diaryentry_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='suggestion',
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
