# Generated by Django 5.2 on 2025-04-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_app', '0013_remove_diaryentry_date_remove_diaryentry_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
